apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-config
  namespace: billing-dev
  labels:
    environment: dev
data:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_USERNAME: "root"
  SPRING_DATASOURCE_OPTIONS: "createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
  # DATASOURCES
  AUTH_DATASOURCE_URL: "jdbc:mysql://mysql:3306/db_authentication?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
  CUSTOMER_DATASOURCE_URL: "jdbc:mysql://mysql:3306/db_customer?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
  CATALOG_DATASOURCE_URL: "jdbc:mysql://mysql:3306/db_catalog?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
  BOUTIQUE_DATASOURCE_URL: "jdbc:mysql://mysql:3306/db_boutique?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
  SUBSCRIPTION_DATASOURCE_URL: "jdbc:mysql://mysql:3306/db_subscription?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
  USAGE_DATASOURCE_URL: "jdbc:mysql://mysql:3306/db_usage?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
  BILLING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/db_billing?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
  #  KAFKA
  KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  SIM_LIFECYCLE_TOPIC: "boutique.sim.lifecycle"
  # MICROSERVICES
  AUTH_SERVICE_URL: "http://authentication-service:8087"
  CUSTOMER_SERVICE_URL: "http://customer-service:8081"
  CATALOG_SERVICE_URL: "http://catalog-service:8082"
  SUBSCRIPTION_SERVICE_URL: "http://subscription-service:8083"
  USAGE_SERVICE_URL: "http://usage-service:8084"
  BILLING_SERVICE_URL: "http://billing-service:8085"
  BOUTIQUE_SERVICE_URL: "http://boutique-service:8088"

  SPRING_PROFILES_ACTIVE: "dev"
  SERVER_SHUTDOWN: "graceful"
