FROM jenkins/jenkins:lts

USER root

# Install docker cli, Maven, and Java 21
RUN apt-get update && \
    apt-get install -y docker.io git curl maven && \
    apt-get clean

RUN usermod -aG docker jenkins

USER jenkins
