pipeline {
    agent { label 'built-in' }
    /*
    
    environment {
        DOCKER_HUB_CREDENTIALS = credentials('dockerhub-credentials')
        DOCKER_IMAGE = 'ghassenchouchen/catalog-service'
    }
    */

    stages {
        stage('Build') {
            steps {
                dir('spring-backend/catalog-service') {
                    sh 'mvn clean package -DskipTests -B'
                }
            }
        }

        stage('Test') {
            steps {
                dir('spring-backend/catalog-service') {
                    sh 'mvn test -B'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('spring-backend/catalog-service') {
                    withSonarQubeEnv('SonarQube') {
                        sh 'mvn sonar:sonar -B'
                    }
                }
            }
        }

        stage('Quality Gate') { 
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        /*stage('Docker Build') {
            steps {
                dir('spring-backend/catalog-service') {
                    sh 'docker build -t ${DOCKER_IMAGE}:${BUILD_NUMBER} -t ${DOCKER_IMAGE}:latest .'
                }
            }
        }*/

        /*stage('Docker Push') {
            steps {
                sh 'echo $DOCKER_HUB_CREDENTIALS_PSW | docker login -u $DOCKER_HUB_CREDENTIALS_USR --password-stdin'
                sh 'docker push ${DOCKER_IMAGE}:${BUILD_NUMBER}'
                sh 'docker push ${DOCKER_IMAGE}:latest'
            }
        }*/
    }

    post {
        always {
            junit 'spring-backend/catalog-service/target/surefire-reports/*.xml'
            publishHTML([
                allowMissing         : false,
                alwaysLinkToLastBuild: true,
                keepAll              : true,
                reportDir            : 'spring-backend/catalog-service/target/site/jacoco',
                reportFiles          : 'index.html',
                reportName           : 'JaCoCo Coverage - Service Catalogue'
            ])
           // sh 'docker logout'
        }
        success {
            echo 'Pipeline succeeded.'
        }
        failure {
            echo 'Pipeline failed. Check logs above.'
        }
    }
}